apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: failfast-ci-worker
  name: failfast-ci-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: failfast-ci-worker
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: failfast-ci-worker
    spec:
      containers:
      - command:
        - celery
        - -A
        - ffci.jobs.runner
        - worker
        - -l
        - debug
        volumeMounts:
          - name: failfast-config
            mountPath: /etc/failfast-ci
        envFrom:
          - configMapRef:
              name: failfast-ci-envs
        env:
        - name: K8S_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: GITHUB_INTEGRATION_PEM
          valueFrom:
            secretKeyRef:
              key: integration_pem
              name: failfast-ci
        - name: FFCI_CONF_FILE
          value: /etc/failfast-ci/failfast-ci.yaml
        image: quay.io/failfast-ci/failfast:v0.6.1
        imagePullPolicy: Always
        name: failfast-ci-worker
      volumes:
        - name: failfast-config
          configMap:
            name: failfast-ci
